@startuml
'https://plantuml.com/class-diagram

package tournament.presentation {
    class TournamentController {
        post(tournament: TournamentDto): String
        get(id: String): TournamentDto
    }

    class ParticipantController {
        post(tournamentId: String, participant: ParticipantDto): String
        delete(id: String)
    }
}

package tournament.application {
    class TournamentUsecase {
        createTournament(tournament: Tournament): String
        getTournament(tournament: Tournament): String
    }

    class ParticipantUsecase {
        addParticipantToTournament(tournamentId: String, participant: Participant)
    }

    package "tournament.application.model" {
        class Tournament {
            name: String
            participants: List<Participant>
        }

        class Participant {
            id: String
            name: String
        }
    }
}

package tournament.persistence {
    class TournamentRepository {
        insert(tournament: TournamentDao): string
        update(tournament: TournamentDao)
        get(id: string): TournamentDao
        delete(id: string)
    }

    class ParticipantRepository {
        insert(participant: ParticipantDao): string
    }
}

TournamentController --> TournamentUsecase
ParticipantController --> ParticipantUsecase
ParticipantUsecase --> TournamentUsecase
ParticipantUsecase --> Participant
TournamentUsecase -right-> Tournament
ParticipantUsecase --> ParticipantRepository
TournamentUsecase -down-> TournamentRepository
Tournament *-right- Participant



@enduml